version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pmdccolleges
      POSTGRES_PASSWORD: "jvAHUXtVE3BAfJdsXNbE3chpmiaCdiob"
    volumes:
      - pmdccolleges_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "6AkqqWaAEDrLxuS09W3EL_uRTXsfO6--"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  pmdccolleges_data:
